export const FORM_VALUES = 'FORM_VALUES';
export const GET_APPLICATION = 'GET_APPLICATION';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const HANDLE_FORM_CHANGES = 'HANDLE_FORM_CHANGES';
export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const EDIT_FORM = 'EDIT_FORM';


export const HANDLE_SEARCH_CHANGES = 'HANDLE_SEARCH_CHANGES';
export const GET_JOB_DATABASE = 'GET_JOB_DATABASE';


//Stats 

export const GET_STATS = 'GET_STATS';