export const FORM_VALUES = 'FORM_VALUES';
export const GET_APPLICATION = 'GET_APPLICATION';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const HANDLE_FORM_CHANGES = 'HANDLE_FORM_CHANGES';
export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const EDIT_FORM = 'EDIT_FORM';